"""
QUALITY.md dashboard generator.

Produces a Markdown report summarising the latest scan that can be committed
to git — providing quality trending without any server infrastructure.
"""

import time
from pathlib import Path
from typing import Optional

from security_scanner.scanner import ScanResult, CRITICAL, HIGH, MEDIUM, LOW


def generate_dashboard(result: ScanResult, project_name: str = "") -> str:
    """Produce a Markdown dashboard from a ScanResult."""
    lines = []

    # Header
    status = "PASS" if result.passed else "FAIL"
    badge = "brightgreen" if result.passed else "red"
    lines.append(f"# Quality Dashboard{' — ' + project_name if project_name else ''}")
    lines.append("")
    lines.append(f"![Status](https://img.shields.io/badge/quality-{status}-{badge})")
    lines.append(f"![Findings](https://img.shields.io/badge/findings-{len(result.findings)}-blue)")
    lines.append(f"![Scanned](https://img.shields.io/badge/files-{result.scanned}-lightgrey)")
    lines.append("")

    # Timestamp
    ts = time.strftime("%Y-%m-%d %H:%M:%S %Z")
    lines.append(f"*Last updated: {ts}*")
    lines.append("")

    # Domain summary table
    if result.domain_results:
        lines.append("## Domain Summary")
        lines.append("")
        lines.append("| Domain | Tool | Findings | Status | Time |")
        lines.append("|--------|------|----------|--------|------|")
        for name, dr in sorted(result.domain_results.items()):
            passed = dr.get("passed", True)
            status_icon = "PASS" if passed else "FAIL"
            elapsed = f"{dr.get('time', 0):.1f}s"
            lines.append(
                f"| {name} | {dr.get('tool', '')} | "
                f"{dr.get('findings', 0)} | {status_icon} | {elapsed} |"
            )
        lines.append("")

    # Severity breakdown
    lines.append("## Severity Breakdown")
    lines.append("")
    crit = result.critical_count
    high = result.high_count
    med = result.medium_count
    low = sum(1 for f in result.findings if f.severity == LOW)
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Critical | {crit} |")
    lines.append(f"| High     | {high} |")
    lines.append(f"| Medium   | {med} |")
    lines.append(f"| Low      | {low} |")
    lines.append(f"| **Total**| **{len(result.findings)}** |")
    lines.append("")

    # Top findings (max 20)
    if result.findings:
        lines.append("## Top Findings")
        lines.append("")
        lines.append("| Severity | Rule | File | Line | Issue |")
        lines.append("|----------|------|------|------|-------|")
        for f in result.findings[:20]:
            lines.append(
                f"| {f.severity} | `{f.rule_id}` | "
                f"`{f.file}` | {f.line} | {f.message} |"
            )
        if len(result.findings) > 20:
            lines.append(f"| ... | ... | ... | ... | *and {len(result.findings) - 20} more* |")
        lines.append("")

    # Errors
    if result.errors:
        lines.append("## Errors")
        lines.append("")
        for err in result.errors[:10]:
            lines.append(f"- {err}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [ai-security-scan](https://github.com/nometria/security-scanner)*")
    lines.append("")

    return "\n".join(lines)


def write_dashboard(
    project_root: Path,
    result: ScanResult,
    filename: str = "QUALITY.md",
    project_name: str = "",
) -> Path:
    """Generate and write the dashboard to the project root.

    Returns the path to the written file.
    """
    content = generate_dashboard(result, project_name=project_name)
    out_path = project_root / filename
    out_path.write_text(content, encoding="utf-8")
    return out_path
